xcodeproj 'AFOAuth2Client Tests'
workspace '../AFOAuth2Client'
inhibit_all_warnings!

def import_pods
  pod 'OCMock', '~> 2.1.1'
  pod 'AFNetworking', '~> 2.0.3'
  pod 'AFOAuth2Client', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end
